name = "CFBoxes"
uuid = "435ea534-530f-4103-a4e2-07b06daf33cf"
authors = ["Benedict Hatton, Thomas Dubos <thomas.dubos@polytechnique.edu>"]
version = "0.0.3"

[deps]
ManagedLoops = "36a4119d-6b73-4371-88fe-ba2d91f5495d"

[compat]
ManagedLoops = "0.1.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
