name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
    uses: ClimFlows/.github/.github/workflows/test.yml@main
    with:
      version: ${{ matrix.version }} 
    secrets: inherit

  docs:
    uses: ClimFlows/.github/.github/workflows/docs.yml@main
    with: 
      package: CFBoxes
    secrets: inherit
